---
git:
  author: 'Phil Watts'
  email: 'pwatts217@gmail.com'
  handle: 'MarsuperMammal'
  organization:
  oauth:
  password:
  provider: 'GitHub'
  private: false
  workspace: '/Users/pwatts/git/'
puppet:
  forge:
    user: 'MarsuperMammal'
  hooks:
    precommit:
      style: true
      syntax: true
    prereceive:
      style: true
      syntax: true
    r10k-webhook:
      enabled: false
      uri:
  skelpath: '/Users/pwatts/git/pw_puppet_generate_skeleton'
